// import Head from "next/head";


// function MetaHead() {
//   return (
//     <Head>
//     <title>Create Next App</title>
//     <meta name="description" content="Generated by create next app" />
//     <link rel="icon" href="/favicon.ico" />
//     <link rel="preconnect" href="https://fonts.googleapis.com" />
//     <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
//     <link
//       href="https://fonts.googleapis.com/css2?family=Nunito:wght@300;500;600;700&family=Poppins:wght@400;500;600;700&display=swap"
//       rel="stylesheet"
//     ></link>
//   </Head>
//   )
// }

// export default MetaHead